### ISSUE TITLE
HS_FLAG_DOTALL  |  HS_FLAG_SOM_LEFTMOST

### ISSUE THREAD

**Issue by sadegh01** [01org/hyperscan#11]
These 2 flags are conflicted .
 When I want to Use   these two flags together   the flag HS_FLAG_SOM_LEFTMOST does not work correctly and at the  eventHandler() function the value of `from` is always `0` zero   !!!

**Comment by jviiret** [comment]
These two flags should definitely work together. Please post a test case with the following information:

* The full expression, flags and mode passed to `hs_compile()`,
* The data being scanned,
* The locations of the matches you are receiving, and where you expect them to be.

**Comment by sadegh01** [comment]
These are my flag's
        flags.push_back(HS_FLAG_DOTALL | HS_FLAG_SOM_LEFTMOST );

This is My pattern to extract javascript  : 
1:/<script[^/][^>]*>(.*?)</script[^>]*>|<javascript[^/][^>]*>(.*?)</javascript[^>]*>/ 

This is My File : 
<script type="text/javascript">//<![CDATA[si_ST=new Date;//]]></script>
lablablab
<script type="text/javascript">//<![CDATA[
_G.HT=new Date;
//]]></script></html>
lablablab

I want to use this (HS_FLAG_DOTALL) to detect New Line and use this (HS_FLAG_SOM_LEFTMOST) to get start point .

**Comment by jviiret** [comment]
I think your escaped markup might have stripped some characters from your pattern - I'm assuming from your description that this is what it should look like: (on github, indenting with four spaces will make their Markdown support render text as code without formatting)

    /<script[^/][^>]*>(.*?)</script[^>]*>|<javascript[^/][^>]*>(.*?)</javascript[^>]*>/

I think the issue here is that you are assuming backtracking semantics, whereas Hyperscan provides automata semantics. This means that instead of providing one "best match" that takes into account greedy/ungreedy repeats, alternation ordering, etc like PCRE, Hyperscan delivers all possible matches for a given regex. In these semantics, there is no difference between `.*` and `.*?`.

This is a fundamental difference from the way that a backtracking matcher like PCRE operates. We have a more detailed description of it in the [Semantics](http://01org.github.io/hyperscan/dev-reference/compilation.html#semantics) section of the [Hyperscan developer reference](http://01org.github.io/hyperscan/dev-reference/index.html).

In this particular case, this is why `SOM_LEFTMOST` is always reporting a `from` offset of zero: your `.*?` repeats in `DOTALL` mode will match any sequence of characters, so the leftmost start of any match is the first occurrence a match for of `<script[^/][^>]*>`, which is the `<script type="text/javascript">` at offset 0 of your file.

I would suggest that the easiest way to use Hyperscan to extract the data between two script tags would be to split your pattern up into four patterns:

    1:/<script[^/][^>]*>/
    2:/</script[^>]*>/
    3:/<javascript[^/][^>]*>/
    4:/</javascript[^>]*>/

You can then track the offsets at which patterns 1 and 2 match, extracting the data between them, and similarly for 3 and 4.

**Comment by sadegh01** [comment]
Dear  jviiret 
   Thank you a lot for your attention and explanation  ;)
