### ISSUE TITLE
hs_compile_ext_multi fails in sanitizer

### ISSUE THREAD

**Issue by starius** [01org/hyperscan#31]
I have compiled hyperscan 4.2.0 with address sanitizer enabled with gcc 4.8.0. Compiler options: `-fsanitize=address`.

```
$ ./bin/unit-hyperscan --gtest_filter=Hyperscan/BadPattern.Block/10
```

Unit test executabled failed.

Raw log: https://gist.github.com/fd1d9298ed40f27d8169f75d7d9bcefa

Log symbolized with asan_symbolize.py and c++filt:
https://gist.github.com/03cc15922e679ac53e7d8a0aca807e16

**Comment by jviiret** [comment]
I could not reproduce this locally with g++-4.8 (Ubuntu 4.8.5-4ubuntu2) on a 64-bit system. 

Can you tell us the arch and OS you're using, as well as a the CMake invocation you used to configure your build?

Have you been able to reproduce this with a different version of GCC?

**Comment by starius** [comment]
Versions:

```
$ gcc --version
gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ uname -a
Linux instance-3 3.19.0-64-generic #72~14.04.1-Ubuntu SMP Fri Jun 24 17:59:48 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.4 LTS
Release:        14.04
Codename:       trusty
```

CMake invokation:
```
$ cmake .. \
-DCMAKE_BUILD_TYPE=Debug \
-DCMAKE_CXX_FLAGS=-fsanitize=address \
-DCMAKE_C_FLAGS=-fsanitize=address \
-DCMAKE_MODULE_LINKER_FLAGS=-fsanitize=address \
-DCMAKE_SHARED_LINKER_FLAGS=-fsanitize=address
```

(The image of the machine is called `Ubuntu 14.04 LTS  amd64 trusty image built on 2016-06-27` in https://console.cloud.google.com )

It is not reproduced with the following version of clang on the same machine:
```
Ubuntu clang version 3.4-1ubuntu3 (tags/RELEASE_34/final) (based on LLVM 3.4)
Target: x86_64-pc-linux-gnu
Thread model: posix
```

I can't reproduce it in Travis CI, which uses the following version of gcc:
```
GCC version
gcc (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3
Copyright (C) 2011 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by jviiret** [comment]
I have taken another look at this issue today, and we have now managed to reproduce it locally. It appears to me to be a false positive from this toolchain, resulting from the use of (a) gcc 4.8.x, (b) `-O2` optimisation, (c) `-march=native` on some platforms, and (d) AddressSanitizer.

If you compile the file `src/parser/Utf8ComponentClass.cpp` with `-O1` or `-O3` (rather than `-O2`), the test passes. Similarly, builds with this gcc on a newer arch (Skylake) pass, as do builds with gcc 5.

The code itself looks innocuous enough -- I can't see our fairly simple use of boost interval_set here leading to a stack overflow in the `std::pair` constructor.

I would suggest that you consider doing any AddressSanitizer testing with a newer toolchain or that you manually set some CXX_COMPILER_FLAGS to reduce the optimization being applied.

**Comment by mdb256** [comment]
I'm going to guess that this is no longer a problem, and that a newer toolchain was the answer. So I'll close the issue for now.
