### ISSUE TITLE
Boost CMake not working

### ISSUE THREAD

**Issue by eplanet** [01org/hyperscan#5]
I think the working of CMake to find the Boost dependancy needs a little fix. While requiring a given version of boost is fine, suggesting to extract it in ${CMAKE_SOURCE_DIR}/include is not working. My understanding for the "hint" BOOST_INCLUDEDIR, is that is suggests to cmake to point to the required Boost installation in that directory, but not to search for the required headers inside that directory.

The proper way definitely seems to point to the boost headers using the BOOST_ROOT variable, and passing it to the script. The script's error message should then suggest the user to pass the following variable as an argument to CMake :
  cmake .. -DBOOST_ROOT=/opt/boost_1_59_0/

The result is CMake working properly and making a symbolic link inside ${CMAKE_SOURCE_DIR}/include to /opt/boost_1_59_0/

P.S: There's a typo in the error message if boost is not found : "... Either install system _**pacakges**_ if available ..."

**Comment by mdb256** [comment]
Thanks for this - fixed in ba0b2b7.

We use a symlink to the headers in include/boost on the vast majority of our testing machines, so we want to retain that method. We have added the description of BOOST_ROOT though as that is a good idea, and fixed a bug in the include_directories() call (_DIRS, not _DIR) so it should now actually work.

**Comment by mdb256** [comment]
But we missed the typo.
