### ISSUE TITLE
Issue in the function  hs_expression_info()

### ISSUE THREAD

**Issue by mkrueger92** [01org/hyperscan#54]
Hi, for me it looks like there is an issue in the function `hs_expression_info()`. 

I expect that the function `hs_expression_info()` has the same behaviour as the compile functions such as `hs_compile()`. I expect that all patterns checked successfully with the `hs_expression_info()` function will also be successfully process by the `hs_compile()` function using the same pattern and flags, but it doesn't.

See the code example below. With a pattern that matches empty buffers and the `HS_FLAG_ALLOWEMPTY` flag NOT set, the two functions behave different. In that case `hs_expression_info()` returns `HS_SUCCESS` but `hs_compile()` fails.

I tested it with the latest sources on GitHub with tag v4.4.1.

```
#include <stdio.h>
#include <unistd.h>

#include "hs.h"

int main(int argc,char* argv[])
{
  unsigned int hs_flags;
  hs_expr_info_t *hs_info = NULL;
  hs_compile_error_t *hs_error = NULL;
  hs_database_t *hs_db; 
  const char pattern[] = ".*";

  hs_flags = HS_FLAG_SINGLEMATCH; // | HS_FLAG_ALLOWEMPTY;

  hs_error_t hs_ret = hs_expression_info(pattern, hs_flags, &hs_info, &hs_error);
  if (hs_ret != HS_SUCCESS)
  {
     printf("Error evaluating regex failed (%d): %s\n", hs_ret, hs_error->message);
     hs_free_compile_error(hs_error);
     return EXIT_FAILURE;
  }
  hs_free_compile_error(hs_error);
  free(hs_info);

  hs_ret = hs_compile(pattern, hs_flags, HS_MODE_BLOCK, NULL, &hs_db, &hs_error);
  if (hs_ret != HS_SUCCESS)
  {
     printf("Error compiling regex failed (%d): %s\n", hs_ret, hs_error->message);
     hs_free_compile_error(hs_error);
     return EXIT_FAILURE;
  }
  hs_free_compile_error(hs_error);
  hs_free_database(hs_db);

  return EXIT_SUCCESS;
}
```

**Comment by jviiret** [comment]
Thanks for the bug report!

This does indeed look like an inconsistency, and I will look into it.

**Comment by jviiret** [comment]
We have investigated this a little further, and we believe that this is a misunderstanding. I have made some changes to the documentation (see c4e2459) to make this clearer.

Essentially, the `hs_expression_info()` and `hs_expression_ext_info()` functions are intended to provide information about an expression, not to be used as a lightweight compile function.

The `HS_FLAG_ALLOWEMPTY` flag has no effect on the output of the function (as it does not change the semantics of the expression itself), so it does not provoke an error just because `hs_compile()` would reject the expression. `HS_FLAG_SOM_LEFTMOST` behaves the same way.

We want these functions to be able to provide useful information about a pattern even if it would fail compilation due to an implementability limitation or a resource limit being exceeded.
