### ISSUE TITLE
Compilation fails with boost 1.58.0 and clang 4.0.1

### ISSUE THREAD

**Issue by fgsch** [01org/hyperscan#62]
clang version 4.0.1-svn305187-1~exp1 (branches/release_40)
boost 1.58.0+dfsg-5ubuntu3.1
hyperscan 4.5.2
Ubuntu xenial

```
/home/fgsch/hyperscan~/unit/internal/graph.cpp:208:5: error: unused typedef 'boost_concept_check208' [-Werror,-Wunused-local-typedef]
    BOOST_CONCEPT_ASSERT((GraphConcept<SimpleG>));
    ^
/usr/include/boost/concept/assert.hpp:43:5: note: expanded from macro 'BOOST_CONCEPT_ASSERT'
    BOOST_CONCEPT_ASSERT_FN(void(*)ModelInParens)
    ^
/usr/include/boost/concept/detail/general.hpp:79:7: note: expanded from macro 'BOOST_CONCEPT_ASSERT_FN'
      BOOST_PP_CAT(boost_concept_check,__LINE__)             \
      ^
/usr/include/boost/preprocessor/cat.hpp:22:32: note: expanded from macro 'BOOST_PP_CAT'
#    define BOOST_PP_CAT(a, b) BOOST_PP_CAT_I(a, b)
                               ^
/usr/include/boost/preprocessor/cat.hpp:29:34: note: expanded from macro 'BOOST_PP_CAT_I'
#    define BOOST_PP_CAT_I(a, b) a ## b
                                 ^
<scratch space>:70:1: note: expanded from here
boost_concept_check208
```

**Comment by mdb256** [comment]
Thanks for pointing this out. We do test older versions of boost, but also need to test that against a wider range of compilers.

This is only a warning, so we can wait to fix this in the next release. We don't enable `-Werror` for default builds (`RelWithDebInfo`) - so that newer/different compilers don't cause unnecessary failures - but do enable it for `CMAKE_BUILD_TYPE=Debug` builds for use in development.

**Comment by mdb256** [comment]
Looking at it a little more: for this particular case it makes more sense to test the compiler for the presence of the warning flag, and then apply it only when building the unit tests - just as we have in [CMakeLists.txt](https://github.com/01org/hyperscan/blob/master/CMakeLists.txt) and [unit/CMakeLists.txt](https://github.com/01org/hyperscan/blob/master/unit/CMakeLists.txt) for the use of `-Wno-unused-variable`. That means it should work on whichever compiler can generate that warning.

(It is more a pity that this isn't a warning that can be ignored by using `-isystem` on Boost headers - the problem is that macro is expanded in our code, not the header, so `-isystem` doesn't save us.)

We shouldn't be disabling this warning generally - we want to pick up if we have this in our code base. Whether we have `-Werror` for all public builds is something else we will consider.

**Comment by fgsch** [comment]
Ok, I will change the PR to follow suit.
